### ISSUE TITLE
gitpod-pharo

### ISSUE THREAD

**Issue by markfirmware** [badetitou/vscode-pharo#1]
See https://github.com/markfirmware/gitpod-pharo#readme

Your system launches a pharo vm to support smalltalk in vscode. Another vision is to have gtoolkit running at all times providing gt advantages to the (limited) vscode ui. In that case, I would imagine vscode lsp client extensions launching json-rpc networking proxies (one per client) each of which connects to the running gt.

There is some discussion in the gtoolkit discord help channel regarding gitpod-gtoolkit, not this little networking detail.

cc @girba

Regards, Mark

**Comment by badetitou** [comment]
Hello @markfirmware 

I'm not sure I get what you want, so I rephrase it.

Instead of the vscode-plugin that starts a Pharo/GT Image. You'd like the GT image to run all the time, and sending a message to this image when you want a LSP for a specific workspace?

If yes: 

Note that LSP can support several workspaces (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders).
How the client (vscode) knows how to communicate with the image.

The LSP and DAP are present here: https://github.com/badetitou/Pharo-LanguageServer
Should be easy to install and play with it. And I might find time to give you a hand

**Comment by markfirmware** [comment]
Thank you. I will proceed with installing vscode-pharo into gitpod-pharo.

**Comment by markfirmware** [comment]
I have installed it without any trouble. I may adapt what you have to use pharo as a language server for languages other than smalltalk.
